Edit for grammar and style
mli/deepnumpy-doc pull request #9
Opened 2019-11-13 06:13 UTC by john-andrilla

In the part where you don't have enough context, I'd suggest not including exercises without proven benefits for the reader. You could always add more context or rationale in a narrative paragraph before the code sample.
@aaronmarkham Can you assist in supplying a less "mathy" demo of the control flows? Also, it's not clear just how the intro under Using Python control flows is connected to the code sample or to the subsection title. Can you add a transition to tie it together?

2019-11-14 22:23 UTC, aaronmarkham requested changes
I don't know of a less mathy way to show the control flow for autograd.
A couple of typos are in here though.

2019-11-14 22:23 UTC, aaronmarkham commented on guide/crash-course/3-autograd.md
> +Consider the following function `f`. The function doubles the inputs until it's `norm` reaches 1000. Then it selects one element depending on the sum of its elements. The following example code
```suggestion
Consider the following function `f` in the following example code. The function doubles the inputs until its `norm` reaches 1000. Then it selects one element depending on the sum of its elements. 
```

2019-11-14 22:23 UTC, aaronmarkham commented on guide/crash-course/3-autograd.md
> +In this exmaple, you record the trace and feed in a random value.
```suggestion
In this example, you record the trace and feed in a random value.
```

2019-11-14 22:23 UTC, aaronmarkham commented on guide/crash-course/3-autograd.md
> +You can see that `b` is a linear function of `a`, and `c` is chosen from `b`. The gradient with respect to `a` be will be either `[c/a[0], 0]` or `[0, c/a[1]]`, depending on which element from `b` is
```suggestion
You can see that `b` is a linear function of `a`, and `c` is chosen from `b`. The gradient with respect to `a` be will be either `[c/a[0], 0]` or `[0, c/a[1]]`, depending on which element from `b` is picked. You see the results of this example with this code:
```

2019-11-18 21:43 UTC, john-andrilla commented
Thanks Aaron, committed all changes.

2019-11-18 22:38 UTC, aaronmarkham approved these changes

2019-11-20 21:46 UTC, merged